width = 1200
height = 780
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GRAY = (100, 100, 100)
HIGHLIGHT = (0, 200, 200)
FADECOLOR = (0, 300, 10)
frase_objetivo = ["Olá, e boas vindas à Patoville!","Eu sou a Miku e te ajudarei a conhecer a cidade.",
                    "Nós estamos na frente da entrada Sul da Praça Central.",
                    "Foi nela onde os fundadores moraram e deram inicio à nossa cidade.",
                    "Hoje, quem mora e cuida dela é minha amiga Capi, a capivara!",
                    "O próximo local para visitarmos será o Hospital",
                    "O Hospital é aquela construção grande no canto da cidade.",
                    "Você consegue chegar até lá?",
                    "*",
                    "Muito bem! Você manda muito no volante!",
                    "Aqui é onde trabalha minha amiga Dra. Celina, a cegonha.",
                    "Ela ajuda a cuidar de famílias que estão esperando para ter um filho.",
                    "Agora, nós iremos visitar o Aquário",
                    "*",
                    "Para chegar, precisamos virar à esquerda aqui",
                    "*",
                    "siga reto agora",
                    "*",
                    "Faça mais uma curva à esquerda",
                    "*",
                    "Por fim, vá reto novamente.",
                    "*",
                    "Muito bem, nós chegamos ao Aquário!",
                    "No Aquário podemos encontrar animais marinhos de todos os cantos do planeta!",
                    "Além disso, toda semana tem shows de natação",
                    "Liderados pelo meu amigo Kadu, o pinguim.",
                    "Próximo daqui, temos o Corpo de Bombeiros",
                    "*",
                    "Para chegar lá, vire à esquerda.",
                    "*",
                    "Agora, vire à direita.",
                    "*",
                    "Vire à esquerda novamente.",
                    "*",
                    "Por fim, vire à direita.",
                    "*",
                    "Parabéns, nós chegamos ao *Corpo de Bombeiros*!",
                    "Sempre dispostos a ajudar quem precisa",
                    "E a combater qualquer incêndio que apareça",
                    "Patoville tem muito orgulho de seus bombeiros.",
                    "Fazendo parte dessa equipe faiscante, temos meu amigo Pingo, o dálmata, sempre o primeiro a enfrentar as chamas.",
                    "Perto daqui fica a Delegacia de Policia.",
                    "O caminho para a delegacia é mais simples.",
                    "*",
                    "Primeiro, vire à direita.",
                    "*",
                    "Vire à direita novamente.",
                    "*",
                    "Agora, siga reto.",
                    "*",
                    "Siga reto novamente.",
                    "*",
                    "Chegamos à Delegacia!",
                    "Os policiais de Patoville são muito bem treinados, e estão sempre trabalhando para manter a paz de todos.",
                    "Liderando o batalhão, temos o meu amigo Major Cavalcante, o Cavalo, controlando a segurança à rédeas curtas!",
                    "Visitaremos agora a Fazenda",
                    "Responsável por grande parte dos alimentos em nossa cidade.",
                    "*",
                    "Para chegar lá, vire à esquerda.",
                    "*",
                    "Vire novamente à esquerda.",
                    "*",
                    "Agora, siga reto.",
                    "*",
                    "Siga reto mais uma vez",
                    "*",
                    "Vire à esquerda uma ultima vez",
                    "*",
                    "Muito bem! chegamos à Fazenda",
                    "Aqui, vários fazendeiros trabalham diariamente cuidando de plantações e pomares.",
                    "Entre eles está minha amiga, Chica, a galinha",
                    "Penando do nascer ao por do Sol.",
                    "Em sequência, vamos conhecer a Escola",
                    "*",
                    "Primeiro, vire à direita",
                    "*",
                    "Agora, vire à esquerda.",
                    "*",
                    "Por fim, vire à esquerda novamente.",
                    "*",
                    "Muito bem!, chegamos aqui sem nenhum problema!",
                    "Foi aqui onde conheci todos os meus amigos e descobri minha paixão por geografia!",
                    "Tudo graças ao melhor professor de todos",
                    "O professor Furôncio, o furão, que sempre incentivou nossa curiosidade.",
                    "Por fim, temos a Prefeitura.",
                    "*",
                    "Para chegar lá basta ir reto até chegar na frente da Prefeitura.",
                    "*",
                    "Quem lidera Patoville hoje é o prefeito Plumário, o papagaio.",
                    "Desde que assumiu, ele ajeitou todas as ruas da cidade.",
                    "Espera, onde está o prefeito?!?!",
                    "Tudo que tem aqui é esse papel.",
                    "Olhe, nesse papel tem direções...",
                    "Mas está usando os pontos cardeais...",
                    "Se usarmos a Rosa dos Ventos da praça",
                    "nós podemos desvendar essa pista!",
                    "*",
                    "Primeiro, vá uma rua para o Oeste",
                    "*",
                    "Agora, vá uma rua para o Sul",
                    "*",
                    "Vá uma rua para o Oeste novamente",
                    "*",
                    "Por fim, mais uma rua ao Sul",
                    "*",
                    "Parece que chegamos onde precisamos",
                    "Há mais um papel aqui.",
                    "*",
                    "Agora precisamos ir todo o caminho para o Leste.",
                    "*",
                    "Por fim, duas ruas para o Norte",
                    "*",
                    "Parece que chegamos ao nosso último destino",
                    "Mas espere, esta é a minha casa!!",
                    "Será que o prefeito está lá dentro?",
                    "Surpresa!!!!",
                    "Para comemorar a sua vinda à nossa cidade,",
                    "resolvemos te fazer essa pequena festinha!",
                    "Espero que tenha gostado de nossa companhia",
                    "e que tenhamos de ajudado",
                    "a entender melhor geografia!",
                    "Um abraço e até a próxima!"]
] 
menu_background = 'menu.png'
menu_jogar = 'menu_click.png'
menu_titulo = 'titulo'
miku_talking_open = 'miku_open.png'
miku_talking_close = 'miku_close.png'
hospital = 'hospital.png'
aquario = 'aquario.png'
estado = 'menu'
frase_atual = ""
index_frase = 0
letra = len(frase_objetivo[index_frase])
music = 0
video_path = 'car_driving.mp4'
hospital_valor = [26, 1456]
aquario_valor = [27, 3091]